<?php
/**
 * @var $this Mage_Core_Block_Template
 */
?>
<table class="border" cellpadding="0" cellspacing="0">
    <thead>
    <tr class="headings">
        <th class="type-image"><?php echo Mage::helper('catalog')->__('Image') ?></th>
        <th class="type-title"><?php echo Mage::helper('catalog')->__('Title') ?> <span class="required">*</span></th>
        <th class="type-price"><?php echo Mage::helper('catalog')->__('Price') ?></th>
        <th class="type-sku"><?php echo Mage::helper('catalog')->__('Sku') ?></th>
        <th class="type-sort"><?php echo Mage::helper('catalog')->__('Sort Order') ?></th>
    </tr>
    </thead>
    <tbody id="swatch_option_type_row_{{id}}">
    </tbody>
</table>